# Generated by Django 4.2.3 on 2023-07-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
