# Generated by Django 4.2.3 on 2023-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='imagen.jpg', upload_to='noticias'),
        ),
    ]
