# Generated by Django 4.2.3 on 2023-07-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
